### ISSUE TITLE
Todo for 0.3.2

### ISSUE THREAD

**Issue by 54wedge** [54wedge/web_builder#1]
### Todo
- [ ] Tag and Category feature remake
  - [ ] Sort tag and category by time
  - [ ] Make their own page for different category and tag
- [ ] unify code style and more comment
